# Generated by Django 5.1 on 2024-08-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="provider",
        ),
        migrations.AddField(
            model_name="user",
            name="business_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "일반 사용자"),
                    ("analyst", "분석가"),
                    ("client", "의뢰자"),
                ],
                default="user",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(
                blank=True,
                choices=[("kakao", "카카오"), ("naver", "네이버"), ("google", "구글")],
                max_length=100,
                null=True,
            ),
        ),
    ]
