# Generated by Django 5.1 on 2024-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_verificationcode_alter_user_options_user_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
