# Generated by Django 5.1 on 2024-08-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_nickname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
    ]
