[tool.poetry]
name = "oz-03-collabo-003-be"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.8"
<<<<<<< HEAD
python-dotenv = "^1.0.1"
djangorestframework = "^3.15.2"
djangorestframework-simplejwt = "^5.3.1"
psycopg2-binary = "^2.9.9"
=======
psycopg2-binary = "^2.9.9"
dnspython = "^2.6.1"
python-dotenv = "^1.0.1"
djangorestframework = "^3.15.2"
djangorestframework-simplejwt = "^5.3.1"
black = "^24.8.0"
isort = "^5.13.2"
>>>>>>> 456bd42e8b974c5740379153839592e2e4f5b771


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
