# Generated by Django 5.1 on 2024-08-28 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="category",
            new_name="main_category",
        ),
        migrations.AddField(
            model_name="content",
            name="semi_category",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
