# Generated by Django 5.1 on 2024-09-02 08:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0003_rename_category_content_main_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qna",
            name="text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qna",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contents.content"
            ),
        ),
    ]
