# Generated by Django 5.1 on 2024-09-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0004_qna_text_alter_qna_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="images",
        ),
        migrations.AddField(
            model_name="contentimage",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.content",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="contentimage",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
