# Generated by Django 5.1 on 2024-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0006_content_likes_count_content_views_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="likes_count",
        ),
        migrations.RemoveField(
            model_name="content",
            name="views_count",
        ),
        migrations.AlterField(
            model_name="contentimage",
            name="file",
            field=models.TextField(blank=True, null=True),
        ),
    ]
