# Generated by Django 5.1 on 2024-08-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contents.content"
            ),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="analysis.analysisrequest",
            ),
        ),
    ]
