# Generated by Django 5.1 on 2024-08-27 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="analyst",
            field=models.ManyToManyField(
                blank=True,
                related_name="analysis_requests_as_analyst",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
