# Generated by Django 5.1 on 2024-08-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_analyst"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyst",
            old_name="photo",
            new_name="analyst_image",
        ),
        migrations.RenameField(
            model_name="analyst",
            old_name="introduction",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="analyst",
            old_name="message",
            new_name="merit",
        ),
        migrations.RenameField(
            model_name="analyst",
            old_name="strengths",
            new_name="summary",
        ),
    ]
