# Generated by Django 5.1 on 2024-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_remove_analysisreport_url_analysisreport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisreport",
            name="file",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analyst",
            name="analyst_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
