# Generated by Django 5.1 on 2024-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_alter_analysisreport_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyst",
            name="analyst_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
