name: Django CD

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Deploy to NCP server
      env:
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        NCP_SERVER_IP: ${{ secrets.NCP_SERVER_IP }}
        NCP_SSH_PRIVATE_KEY: ${{ secrets.NCP_SSH_PRIVATE_KEY }}
      run: |
        # .env 파일 생성 (heredoc 사용)
        cat << EOF > .env
        DB_ENGINE=$DB_ENGINE
        DB_NAME=$DB_NAME
        DB_USER=$DB_USER
        DB_PASSWORD=$DB_PASSWORD
        DB_HOST=$DB_HOST
        DB_PORT=$DB_PORT
        EOF

        # SSH 키 등록
        mkdir -p ~/.ssh
        echo "$NCP_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # NCP 서버에 접속하여 배포 스크립트 실행 (수정된 부분)
        ssh -o StrictHostKeyChecking=no root@$NCP_SERVER_IP "
          # 작업 디렉토리 설정
          cd /path/to/your/project && \
          # develop 브랜치의 최신 코드 가져오기 및 체크아웃
          git fetch origin develop && \
          git checkout develop && \
          # Docker 이미지 빌드 (이동된 부분)
          docker-compose build && \
          # 배포 스크립트 실행
          bash ./deploy.sh
        "